name: Caching Dependencies

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: my-cache
          key: cache-f72f708

      - name: Generate Cache Content
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          mkdir -p my-cache
          echo "dependencies cached" > my-cache/deps.txt

      - name: prime-cache-f72f708
        run: echo "Cache hit ${{ steps.cache-deps.outputs.cache-hit }}"
